# Generated by Django 4.2.6 on 2023-10-25 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(blank=True, max_length=500)),
                ('room_number', models.PositiveIntegerField()),
                ('capacity', models.IntegerField()),
                ('floor_number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('executive', 'executive'), ('regular', 'regular')], max_length=300)),
                ('status', models.CharField(choices=[('free', 'free'), ('occupied', 'occupied')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookroom.room')),
            ],
        ),
    ]
