# Generated by Django 4.2.6 on 2023-10-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0002_alter_bookroom_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookroom',
            name='book_time_over',
        ),
    ]
