# Generated by Django 4.2.6 on 2023-11-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
