# Generated by Django 4.2.6 on 2023-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0003_remove_bookroom_book_time_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('free', 'free'), ('occupied', 'occupied')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('executive', 'executive'), ('regular', 'regular')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
