# Generated by Django 4.2.6 on 2023-10-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0004_room_status_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
