# Generated by Django 4.2.6 on 2023-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0006_remove_bookroom_user_room_capacity_room_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.CharField(max_length=500),
        ),
    ]
