# Generated by Django 4.2.6 on 2023-11-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_bool',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
