# Generated by Django 4.2.6 on 2023-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_payment_bool_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
