# Generated by Django 3.2 on 2023-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_floors', models.PositiveIntegerField()),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_fitness_center', models.BooleanField(default=False)),
                ('opening_date', models.DateField()),
                ('last_renovation_date', models.DateField()),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
